### ISSUE TITLE
Fix Sign Up Button

### ISSUE THREAD

**Issue by christyeicher** [christyeicher/dark.horse#21]

**Comment by cablio** [comment]
Signup implemented. No button, though.

**Comment by christyeicher** [comment]
Sign Up is giving me "username taken" error every time. I've checked the local db, and the username isn't taken.

**Comment by cablio** [comment]
I just tested it and it worked.

**Comment by christyeicher** [comment]
It's because I hadn't rerun CreateDB.php.................._slits wrists_
