### ISSUE TITLE
Upload Button ABOVE Every Image

### ISSUE THREAD

**Issue by christyeicher** [christyeicher/dark.horse#30]

**Comment by cablio** [comment]
Are you kidding?

**Comment by cablio** [comment]
No, dummy. Above "ANY".
So, our links can be made buttons.

**Comment by christyeicher** [comment]
Oh thank Jesus. Wow. I'll make them buttons right now.

**Comment by cablio** [comment]
I'm working on it.

**Comment by cablio** [comment]
Done. It's only for upload, so we can get away with that.
