### ISSUE TITLE
Add abstract render($data) functions to base classes

### ISSUE THREAD

**Issue by christyeicher** [christyeicher/dark.horse#5]

**Comment by cablio** [comment]
src/controller/Controller.php has HTML code in it. Will work on that.
src/models/Model.php has HTML code in it. Will work on that.
All the view classes have render, but the main class needs the abstract method. Will do that.
The whole thing will need heavy refactoring after it's done.

**Comment by cablio** [comment]
I read the specs again. Apparently abstract render is just for views, helpers, and elements. This is done.
