### ISSUE TITLE
Add header comment blocks to all files

### ISSUE THREAD

**Issue by christyeicher** [christyeicher/dark.horse#6]
Because we're professionals. Here's a template I found at pear.php.net. We likely won't keep most of those things.

/**
- Short description for file
  *
- Long description for file (if any)...
  *
- PHP version X
  *
- LICENSE: This source file is subject to version 3.01 of the PHP license
- that is available through the world-wide-web at the following URI:
- http://www.php.net/license/3_01.txt.  If you did not receive a copy of
- the PHP License and are unable to obtain it through the web, please
- send a note to license@php.net so we can mail you a copy immediately.
  *
- @category   CategoryName
- @package    PackageName
- @author     Original Author author@example.com
- @author     Another Author another@example.com
- @copyright  1997-2005 The PHP Group
- @license    http://www.php.net/license/3_01.txt  PHP License 3.01
- @version    SVN: $Id$
- @link       http://pear.php.net/package/PackageName
- @see        NetOther, Net_Sample::Net_Sample()
- @since      File available since Release 1.2.0
- @deprecated File deprecated in Release 2.0.0
  */

**Comment by cablio** [comment]
http://www.themillergroup.com/wp-content/uploads/2015/01/JCLdMDveAn.png?4be9bf

**Comment by christyeicher** [comment]
LOL
