### ISSUE TITLE
HTML5 Validate

### ISSUE THREAD

**Issue by christyeicher** [christyeicher/dark.horse#7]
[https://html5.validator.nu/](https://html5.validator.nu/)

**Comment by cablio** [comment]
index.php does not validate because <img> lack alt='text'
Will fix that.

**Comment by cablio** [comment]
Just fixed index.php to validate as HTML5. 
Login, signup, log out, upload are in progress.

**Comment by christyeicher** [comment]
Nice. I'm going to leave this open, because we should re-validate right before we turn in the assignment. Thanks dude!
